config/routes.rb
SampleApp::Application.routes.draw do
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	
	root to: 'static_pages#home'

	match '/signup' ,    to: 'Users#new'
	match '/show' ,      to: 'Users#show'
	match '/help' ,      to: 'static_pages#help'
	match '/galary' ,      to: 'static_pages#galary'
	match '/about' ,     to: 'static_pages#about'
	match '/contact' ,   to: 'static_pages#contact'
	match '/signin',     to: 'sessions#new'
	match '/sessions',   to: 'sessions#create'
	match '/signout',    to: 'sessions#destroy', via: :delete
end

app/views/layouts/_about.html.erb
<!-- Button to trigger modal -->

<!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel" align="center">Y.samuel santhosh</h3>
  </div>
  <div class="modal-body">

    <div class="accordion" id="accordion2">

      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
           Work
         </a>
       </div>
       <div id="collapseOne" class="accordion-body collapse in">
        <div class="accordion-inner">
          Currently I working as a web developer in Arrivu Systems
          <br>
          Job Description:
          <br>
          web Applications developing using ruby on rails.
        </div>
      </div>
    </div>
    
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
          Under Graduate
        </a>
      </div>
      <div id="collapseTwo" class="accordion-body collapse">
        <div class="accordion-inner">
          I have compeleted B.E Computer Sciense in SNS COLLEGE OF TECHNOLOGY coimbatore.
          <br>
          Joined Year:2009
          <br>
          Completed Year:2012
        </div>
      </div>
    </div>

    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
          Diploma
        </a>
      </div>
      <div id="collapseThree" class="accordion-body collapse">
        <div class="accordion-inner">
          I have compeleted Diploma in Computer Sciense in SREE KRISHNA POLYTECHNIC COLLEGE Nagercoil.
          <br>
          Joined Year:2006
          <br>
          Completed Year:2009
        </div>
      </div>
    </div>


    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
          Schooling
        </a>
      </div>
      <div id="collapseFour" class="accordion-body collapse">
        <div class="accordion-inner">
          I did my schooling in LMS HIGHER SECONDARY ZIONPURAM
          <br>
          Completed Year:2006
        </div>
      </div>
    </div>


    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="https://facebook.com/samuels410">Follow me on Facebook</a>
		by samuel santhosh
	</small>
	<nav>
		<ul>
			<li><%= link_to "Photos",galary_path %></li>
			<li><%= link_to "Contact Me", contact_path %></li>
			<li><a href="http://lankasri.com">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_galary.html.erb
<!-- Button to trigger modal -->

<!-- Modal -->
<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel" align="center">Photo Gallary </h3>
  </div>
  <div class="modal-body" align="center">

<ul class="thumbnails" align="center">
  <li class="span4">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("1.jpg")%>
      <h3>Sun flower</h3>
    </div>
  </li>
  <li class="span4">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("2.jpg")%>
      <h3>Parachute</h3>
    </div>
  </li>
  <li class="span4">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("3.jpg")%>
      <h3>Tajmahal</h3>
    </div>
  </li>
  <li class="span4">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("4.jpg")%>
      <h3>Landscape bridge</h3>
    </div>
  </li>
</ul>


  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>


  </div>

</div>

app/views/layouts/_header.html.erb
<header class="navbar  navbar-fixed-top navbar-inverse ">
	<div class="navbar-inner">
		<div class="container">
			<h4 id="logo">Samuel santhosh</h4>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Galary", galary_path %></li>
					<li><%= link_to "Contact Me", contact_path %></li>
					
				</ul>
			</nav>
		</div>
	</div>
	
</header>	

<div class="row1">
	<aside class="span2">

		<table class="table table-hover hero-unit" >
			
			<tr><td>
				<a href="#myModal1" role="button" class="btn btn-block btn-info" data-toggle="modal">About Me</a>
			</td></tr>
			<tr><td>
				<a href="#myModal" role="button" class="btn btn-block btn-info" data-toggle="modal">Contact</a>
				<!-- Button to trigger modal -->

				<!-- Modal -->
				<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel" align="center">Contact me</h3>
					</div>
					<div class="modal-body hero-unit">
						<h4> Mobile Number:</h4>

						+91-9629171382 <br>

						<h4> Email:</h4>
						samuels410@gmail.com <br>
						samuel@arrivusystems.com <br>

						<h4> Facebook</h4>

						http://facebook.com/samuels410

						<h4> Address For Communication:</h4>
						Y.samuel santhosh ,<br>
						Zionpuram, <br>
						M.K.Pottal Post, <br>
						Kanyakumari District, <br>
						629501. <br>

					</div>
				</div>
			</td></tr>
			<tr><td>

				<a href="#myModal3" role="button" class="btn btn-block btn-info" data-toggle="modal">Galary</a>
				<!-- Button to trigger modal -->

				<!-- Modal -->
				<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel" align="center">Photo Gallary </h3>
					</div>
					<div class="modal-body" align="center">

						<ul class="thumbnails" align="center">
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("6.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g2.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g3.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g4.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
						</ul>


					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>


					</div>

				</div>

			</td></tr>


		</table>
	</aside>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head >
	<title>Welcome | samuel santhosh</title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
		<%= render 'layouts/header' %>

</head>
<body .carousel('next')>

<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= render 'layouts/about' %>



</div>
</body>
</html>